### ISSUE TITLE
v4.0 discussion

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender-gulp#5]
## Why a major version

a) Upgrade webpack to v2
b) Potentially make other major changes to our build pipeline

## a) Upgrade webpack to v2

Not much to say here, we wouldn't really notice the upgrade besides smaller bundles (win!) and maybe a cleaner code splitting syntax (currently the `require.resolve` thing).

### New features we could look at:

- Webpack can throw a warning when an asset is larger than a recomended size, which would enforce us to split our js more often for optimization (could be nice, could be a hassle).

### TypeScript

It would be nice to be able to use TypeScript.

#### Pros

- We could replace babel with TS. This means no more 1001 babel dependencies that we need to add to our package.json files. Alos, no decisions for ESNext features, we use whatever TypeScript ships.
- Type checking 😍

#### Cons

- It might suck. We won't know until we try it, 3rd party library type definitions could be an issue, mixing with plain JS might solve this.

### `.vue` file usage

Do we want to keep using `.vue` files?

#### Pros

- Precompiles template for better performance
- Vue community seems to like them, but they're not necessarily pushed as the 'one way'

#### Cons

- Large overhead in the asset pipeline
- Makes it harder to add tools to our workflow (e.g. TypeScript, ESLint)
- Less support in editors (e.g. weaker autocomplete, syntax highlighting)

Without `.vue` files, we would just use Vue's runtime build which is less performant (but this might not really matter for our use case). There are always workarounds to gain perf in critical parts of an app if necessary.

**Comment by freekmurze** [comment]
- Upgrade to webpack v2: just do it 🚀 
- TypeScript: you know I'm a fan of strictness, so I'm fond of this idea. Ditching Babel is nice too. What kind of problems might we have with 3th party definition code?
- .vue files: torn on this one. I kinda like them too. What overhead does this introduce in our asset pipeline? I thought there was only one vueify plugin needed to support this.

**Comment by willemvb** [comment]
- Webpack 2: yes!
- Typescript: no experience, but I can see myself waving goodbye at .babelrc and babel presets already.
- Vue: objective should be speed for developers in development. In production speed is reserved for end users. Is it possible to precompile Vue only on `--production?`

Also:
- evaluate `gulp webpack`: I never use this
- evaluate `gulp svg`: often forget to use this, and put my files directly in public folder. Not sure about the origin `resource/assets/svg`. 
- evaluate `gulp lint:sass`: I'm using csscomb these days mostly for code style fixing.
- should we look into postcss again? Not sure what the gains would be if we mimic all Sass funcitonality.

**Comment by sebastiandedeyne** [comment]
Will look in to using Vue files + TS together. We should test drive TS first though, see how it goes with how we write code (especially page scripts like Masonry, etc).

- `gulp webpack` exists for internal use (the `default` task is `webpack` + `svg`)
- `gulp svg` and `gulp lint:sass` are up to you
- Postcss: also up to you. I rewrote my personal site using modern css (`calc`, `--var`) and it provided enough functionality for me plus standard syntax, so it was a win over sass in my context. Mimicing sass would be pointless, writing modern vanilla scss and preprocessing it would be nice imo (but you need to look in to mixins etc.)

**Comment by sebastiandedeyne** [comment]
Wild idea: if we're gonna thin out, why not just dump gulp and use webpack as is ¯\\\_(ツ)\_/¯

**Comment by sebastiandedeyne** [comment]
Actually, based on what it currently looks like, we could dump blender-gulp all together and just add some extra's to Laravel's new build tool

https://github.com/JeffreyWay/laravel-mix-example

**Comment by sebastiandedeyne** [comment]
Deprecated in favor of Laravel Mix.

Goodnight sweet prince.

😴 ❤️
